version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static-volume:/app/Bodhi/static
      - media-volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.db

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: 'celery -A Bodhi worker -l info'

  redis:
    image: redis:latest

  db:
    image: postgres:16
    restart: always
    env_file:
      - ./.env.db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  static-volume:
  media-volume:
