# Generated by Django 5.0.5 on 2024-05-14 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('course_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Course UID')),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('lesson_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Lesson UID')),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_lesson', to='courses.courses')),
            ],
            options={
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('module_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Module UID')),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_module', to='courses.courses')),
            ],
            options={
                'verbose_name_plural': 'Modules',
            },
        ),
    ]
