# Generated by Django 5.0.5 on 2024-05-14 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_lesson_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_lesson', to='courses.module'),
        ),
    ]
