# Generated by Django 5.0.5 on 2024-05-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Course UID'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_id',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Lesson UID'),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_id',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Module UID'),
        ),
    ]
