# Generated by Django 5.0.5 on 2024-05-19 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courses_is_deleted_lesson_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='is_assessment_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='courses.category'),
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_level', to='courses.level'),
        ),
    ]
