# Generated by Django 5.0.5 on 2024-05-19 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_category_level_courses_is_assessment_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='Course UID'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='level',
            field=models.ManyToManyField(blank=True, related_name='course_level', to='courses.level'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_id',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='Lesson UID'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='module_id',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='Module UID'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='Public identifier')),
                ('course_detail_id', models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='Course Detail UID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_details', to='courses.courses')),
                ('level_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_details_level', to='courses.level')),
            ],
            options={
                'verbose_name_plural': 'CourseDetails',
            },
        ),
    ]
