# Generated by Django 5.0.5 on 2024-05-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_module_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
