# Generated by Django 5.0.5 on 2024-05-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coursedetails_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
    ]
