# Generated by Django 5.0.5 on 2024-05-25 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_module_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='course_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_details_module', to='courses.coursedetails'),
        ),
    ]
