# Generated by Django 5.0.5 on 2024-05-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('OTP', 'OTP'), ('PASSWORD', 'PASSWORD')], default='PASSWORD', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('SUPER ADMIN', 'SUPER ADMIN'), ('TUTOR', 'TUTOR'), ('STUDENTS', 'STUDENTS')], max_length=20, null=True),
        ),
    ]
