# Generated by Django 5.0.5 on 2024-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_login_type_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.CharField(blank=True, choices=[('OTP', 'OTP'), ('PASSWORD', 'PASSWORD')], max_length=10, null=True),
        ),
    ]
