# Generated by Django 5.0.5 on 2024-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_login_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('SUPER ADMIN', 'SUPER ADMIN'), ('TUTOR', 'TUTOR'), ('STUDENT', 'STUDENT')], max_length=20, null=True),
        ),
    ]
