# Generated by Django 5.0.5 on 2024-05-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_interests', to='accounts.interest'),
        ),
    ]
